import type { AgentArchetype } from '../../contracts/vnext'

export const BUILTIN_AGENT_ARCHETYPES: AgentArchetype[] = [
  {
    id: 'semantic-fidelity',
    slug: 'semantic-fidelity',
    displayNameZh: '语义忠实译者',
    category: 'foundation',
    tags: ['通用', '准确', '歧义', '逻辑'],
    isBuiltin: true,
  },
  {
    id: 'target-naturalness',
    slug: 'target-naturalness',
    displayNameZh: '目标语表达译者',
    category: 'expression',
    tags: ['通用', '自然', '母语表达', '搭配'],
    isBuiltin: true,
  },
  {
    id: 'voice-register',
    slug: 'voice-register',
    displayNameZh: '文体声音译者',
    category: 'expression',
    tags: ['文体', '人物声音', '语域', '时代感'],
    isBuiltin: true,
  },
  {
    id: 'terminology',
    slug: 'terminology',
    displayNameZh: '术语一致性译者',
    category: 'domain',
    tags: ['术语', '技术', '学术', '专名'],
    isBuiltin: true,
  },
  {
    id: 'cultural-context',
    slug: 'cultural-context',
    displayNameZh: '意象与专名助手',
    category: 'domain',
    tags: ['前置分析', '意象', '专有名词', '文化', '典故'],
    isBuiltin: true,
  },
  {
    id: 'long-context',
    slug: 'long-context',
    displayNameZh: '长文本连贯译者',
    category: 'foundation',
    tags: ['长文本', '连贯', '指代', '时间线'],
    isBuiltin: true,
  },
  {
    id: 'formal-regulated',
    slug: 'formal-regulated',
    displayNameZh: '规范文本译者',
    category: 'domain',
    tags: ['法律', '政策', '商务', '合规'],
    isBuiltin: true,
  },
  {
    id: 'literary-prose',
    slug: 'literary-prose',
    displayNameZh: '文学叙事译者',
    category: 'creative',
    tags: ['小说', '散文', '叙事', '意象链'],
    isBuiltin: true,
  },
  {
    id: 'poetry-form',
    slug: 'poetry-form',
    displayNameZh: '诗歌韵律译者',
    category: 'creative',
    tags: ['诗歌', '格律', '押韵', '诗行'],
    isBuiltin: true,
  },
  {
    id: 'dissenting',
    slug: 'dissenting',
    displayNameZh: '异议译者',
    category: 'adversarial',
    tags: ['异议', '多义', '反共识', '替代解释'],
    isBuiltin: true,
  },
]
